version: '2'

services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    container_name: web
    volumes_from:
      - app
    ports:
      - 8080:80
  

volumes:
  dbdata:
